### ISSUE TITLE
Documentación de la entrevista Huerto el Mamey 

### ISSUE THREAD

**Issue by Edwin-1012** [SistemasTecTlaxiaco/entrevista-entrevista-gp#3]
[Documentación Preguntas_Taoli, Iván, Alexis, Edwin..pdf](https://github.com/SistemasTecTlaxiaco/entrevista-entrevista-gp/files/7150437/Documentacion.Preguntas_Taoli.Ivan.Alexis.Edwin.pdf)

**Comment by EDITH-R** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
